/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package assignment1_ct417_driver;

public class Library {
    
	public boolean someLibraryMethod() {
        return true;
    }

}
